### ISSUE TITLE
support linux

### ISSUE THREAD

**Issue by vearne** [rfyiamcool/pgcacher#11]
(py3_env) bin % pgcacher -top 5
2023/03/16 11:32:15 pgcacher only support running on Linux !!!

**Comment by vearne** [comment]
(py3_env) bin % pgcacher -top 5
2023/03/16 11:32:15 pgcacher only support running on Linux !!!

**Comment by rfyiamcool** [comment]
There is no directory similar to /proc/{pid}/fd on mac os, no solution found.
